# Generated by Django 5.1.6 on 2025-02-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_products_order_items_order_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='products',
        ),
    ]
