# Generated by Django 5.1.6 on 2025-02-21 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_unique_together'),
        ('orders', '0005_rename_item_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('online', 'Онлайн оплата')], default='cash', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
